routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\IncidenciaController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MisIncidenciaController;
use App\Http\Controllers\Admin\ModoController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SubcategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\EstatuController;
use App\Models\Estatu;
use Illuminate\Support\Facades\Route;

Route::get('', [HomeController::class, 'index'])->middleware('can:admin.home')->name('admin.home');

Route::resource('users', UserController::class)->only(['index', 'edit', 'update'])->names('admin.users');

Route::resource('roles', RoleController::class)->names('admin.roles');

Route::resource('categories', CategoryController::class)->except('show')->names('admin.categories');

Route::resource('subcategories', SubcategoryController::class)->except('show')->names('admin.subcategories');

// Route::resource('modos', ModoController::class)->except('show')->names('admin.modos');
Route::resource('estatus', EstatuController::class)->except('show')->names('admin.estatus');

Route::resource('incidencias', IncidenciaController::class)->except('show')->names('admin.incidencias');

Route::resource('mis-incidencias', MisIncidenciaController::class)->except('show')->names('admin.mis-incidencias');

routes/web.php
<?php

use App\Http\Controllers\IncidenciaController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SuscripcionController;
use Illuminate\Support\Facades\Route;



// Route::get('/',[IncidenciaController::class, 'index'])->name('incidencias.index');
Route::get('/',[IncidenciaController::class, 'index'])->name('incidencias.index')->middleware('auth');

Route::get('incidencias/{incidencia}',[IncidenciaController::class, 'show'])->name('incidencias.show');

Route::get('category/{category}', [IncidenciaController::class, 'category'])->name('incidencias.category');

// Route::get('modo/{modo}', [IncidenciaController::class, 'modo'])->name('incidencias.modo');

// Route::resource('suscripciones', SuscripcionController::class)->names('suscripciones');


/* Mensaje */
Route::post('/mensajes',[MessageController::class, 'store'])->name('mensajes.store');


Route::get('markAsRead', function () {
    auth()->user()->unreadNotifications->markAsRead();
    return redirect()->back();
})->name('markAsRead');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/Admin/IncidenciasIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

use App\Models\Incidencia;

use Livewire\WithPagination;

class IncidenciasIndex extends Component
{

    use WithPagination;

    public $search;

    // para que la paginación funcione con los estilos de boostrap
    protected $paginationTheme = 'bootstrap';

    //Se activa unicamente cuando el valor de la propiedad search cambia y resetea la paginación
    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {

        $myincidencias = Incidencia::where('user_id', auth()->user()->id)
                        // ->where('name', 'LIKE', '%' . $this->search . '%')
                        ->where('titulo', 'LIKE', '%' . $this->search . '%')
                        ->latest('id')
                        ->paginate(10);
        
        //todas las incidencias

        // $incidencias = Incidencia::where('status', 2)
        //                 ->where('name', 'LIKE', '%' . $this->search . '%')
        //                 ->latest('id')
        //                 ->paginate();

        // $incidencias = Incidencia::latest('id')->paginate(8);

        $allincidencias = Incidencia::where
        // ->where('name', 'LIKE', '%' . $this->search . '%')
        ('titulo', 'LIKE', '%' . $this->search . '%')
        ->latest('id')
        ->paginate(10);

        //codigo condicional para mostrar las incidencias del usuario cuando el id es Admin o gestor
        if(auth()->user()->hasRole('Admin')){
            $incidencias = $allincidencias;
        }else{
            $incidencias = $myincidencias;
        }
        return view('livewire.admin.incidencias-index', compact('incidencias'));
    }
}

app/Http/Livewire/Admin/MisIncidenciasIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

use App\Models\Incidencia;

use Livewire\WithPagination;

class MisIncidenciasIndex extends Component
{
    use WithPagination;

    public $search;
    
    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $incidencias = Incidencia::where('user_id', auth()->user()->id)
                        // ->where('name', 'LIKE', '%' . $this->search . '%')
                        ->where('titulo', 'LIKE', '%' . $this->search . '%')
                        ->latest('id')
                        ->paginate(10);
        return view('livewire.admin.mis-incidencias-index', compact('incidencias'));
    }
}

app/Http/Livewire/Admin/SelectComponent.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Category;
use App\Models\Subcategory;
use Livewire\Component;

class SelectComponent extends Component
{
    public $category, $subcategory;
    public $categories = [], $subcategories = [];
    // public $category=null, $subcategory=null;
    // public $categories = null, $subcategories = null;

    public function mount()
    {
        $this->categories = Category::all();
        $this->subcategories = collect();
    }

    public function updatedCategory($valor)
    {
        $this->subcategories = Subcategory::where('category_id', $valor)->get();

        $this->subcategory = $this->subcategories->first()->id ?? null;

    }
    
    public function render()
    {
        return view('livewire.admin.select-component');
    }
}

app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Illuminate\Support\Facades\DB;
use Livewire\Component;

use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;

    public $search;
    
    protected $paginationTheme = 'bootstrap'; 

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $users = User::where('name', 'LIKE', '%' . $this->search . '%')
                    ->orwhere('email', 'LIKE', '%' . $this->search . '%')
                    ->paginate();

        return view('livewire.admin.users-index', compact('users'));
    }
}

app/Http/Livewire/ChatIncidencias.php
<?php

namespace App\Http\Livewire;

use App\Models\Incidencia;
use App\Models\Message;
use App\Models\User;
use Livewire\Component;

class ChatIncidencias extends Component
{
    public $user;
    public $mensaje;
    public $incidencia;
    
    public function mount(Incidencia $incidencia, Message $messages)
    {
        $this->user = "";
        $this->messages = $messages;
        $this->incidencia = $incidencia;
    }

    public function render()
    {
        // $incidencia = Incidencia::where('id', '$incidencia->id')->get();
        // $incidencia = Incidencia::all();
        return view('livewire.chat-incidencias'/* , compact('incidencia') */);
    }

    /* esto es para probar mas adelante */
    public function enviarMensaje()
    {
        /* Message::create([
            'message' => $this->mensaje,
        ]); */

        // $this->emit("mensajeEnviado");

    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Category;

class Navigation extends Component
{
    public function render()
    {
        $categories = Category::all();
        return view('livewire.navigation', compact('categories'));
    }
}

resources/views/livewire/admin/incidencias-index.blade.php
<div class="card">

    <div class="card-header">
        <input wire:model="search" class="form-control" placeholder="Ingrese el nombre de incidencia">
    </div>
    
    @if ($incidencias->count())

        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Usuario</th>
                        <th>Título</th>
                        {{-- <th>Categoría</th> --}}
                        <th>Prioridad</th>
                        <th>Estatu</th>
                        <th>Creación incidencia</th>
                        <th>Última modificación</th>
                        <th>Asignado</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>

                <tbody>
                    
                    @foreach ($incidencias as $incidencia)
                        <tr>
                            <td>{{ $incidencia->id }}</td>
                            <td>{{ $incidencia->user->name }}</td>
                            <td>{{ $incidencia->titulo }}</td>
                            {{-- <td>{{ $incidencia->subcategory->category->name }}</td> --}}
                            <td>{{ $incidencia->emergency->name }}</td>

                            {{-- <td>{{ $incidencia->estatu->name }}</td> --}}
                            <td class="project-state"><span class="badge badge-{{ $incidencia->estatu->color }}">{{ $incidencia->estatu->name }}</span></td>

                            <td>{{ $incidencia->created_at }}</td>
                            <td>{{ $incidencia->updated_at }}</td>
                            <td> Sin asignar </td>

                            <td width="10px">
                                <a class="btn btn-primary btn-sm" href="{{ route('admin.incidencias.edit', $incidencia) }}" title="Editar">
                                    <i class="fas fa-pencil-alt" >
                                    </i>
                                    {{-- Editar --}}
                                </a>
                            </td>
                            <td width="10px">
                                <form action="{{ route('admin.incidencias.destroy', $incidencia) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm" title="Eliminar">
                                        <i class="fas fa-trash">
                                        </i>
                                        {{-- Eliminar --}}
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="card-footer">
            {{ $incidencias->links() }}
        </div>
    @else
        <div class="card-body">
            <strong>No hay ningún registro...</strong>
        </div>
    @endif

</div>

resources/views/livewire/admin/mis-incidencias-index.blade.php
<div class="card">
    <div class="card-header">
        <input wire:model="search" class="form-control" placeholder="Ingrese el nombre de incidencia">
    </div>
    
    @if ($incidencias->count())

        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        {{-- <th>Usuario</th> --}}
                        <th>Título</th>
                        <th>Categoría</th>
                        <th>Prioridad</th>
                        <th>Estatu</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>

                <tbody>
                    
                    @foreach ($incidencias as $incidencia)
                        <tr>
                            <td>{{ $incidencia->id }}</td>
                            {{-- <td>{{ $incidencia->user->name }}</td> --}}
                            <td>{{ $incidencia->titulo }}</td>
                            <td>{{ $incidencia->subcategory->category->name }}</td>
                            <td>{{ $incidencia->emergency->name }}</td>
                            {{-- <td>{{ $incidencia->estatu->name }}</td> --}}
                            <td class="project-state"><span class="badge badge-{{ $incidencia->estatu->color }}">{{ $incidencia->estatu->name }}</span></td>
                            <td width="10px">
                                <a class="btn btn-primary btn-sm" href="{{ route('admin.incidencias.edit', $incidencia) }}" title="Editar">
                                    <i class="fas fa-pencil-alt" >
                                    </i>
                                    {{-- Editar --}}
                                </a>
                            </td>
                            <td width="10px">
                                <form action="{{ route('admin.incidencias.destroy', $incidencia) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm" title="Eliminar">
                                        <i class="fas fa-trash">
                                        </i>
                                        {{-- Eliminar --}}
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="card-footer">
            {{ $incidencias->links() }}
        </div>
    @else
        <div class="card-body">
            <strong>No hay ningún registro...</strong>
        </div>
    @endif

</div>

resources/views/livewire/admin/select-component.blade.php
<div>

    <div class="form-group">
        <label>Categoría*</label>
        {{-- <select name="" id=""></select> --}}
        <select class="form-control" wire:model="category" name="category_id">
            {{-- <option selected>Seleccione una categoría</option> --}}
            <option value="">Seleccione una categoría</option>
            @foreach ($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>

        @error('category_id')
            <small class="text-danger">{{ $message }}</small>
        @enderror
    </div>
    
    
    <div class="form-group">
        <label>Subcategoría*</label>
        <select class="form-control" wire:model="subcategory" name="subcategory_id">
            @if ($subcategories->count() == 0)
                {{-- <option selected>No hay subcategorías</option> --}}
                <option value="">Debe seleccionar una Categoría</option>
            @endif
            
            @foreach ($subcategories as $subcategory)
                <option value="{{ $subcategory->id }}">{{ $subcategory->name }}</option>
            @endforeach
            
        </select>

        @error('subcategory_id')
            <small class="text-danger">{{ $message }}</small>
        @enderror
    </div>

</div>

resources/views/livewire/admin/users-index.blade.php
<div>
    <div class="card-header">
        <input wire:model="search" class="form-control" placeholder="Ingrese nombre o correo de un usuario">
    </div>

    @if ($users->count())
        <div class="card">
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th colspan="2"></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td> {{$user->id}} </td>
                                <td> {{$user->name}} </td>
                                <td> {{$user->email}} </td>
                                <td width="10px">
                                    <a class="btn btn-primary" href="{{ route('admin.users.edit', $user) }}">Editar</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="card-footer">
                {{ $users->links() }}
            </div>
        </div>
    @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
    @endif

</div>