routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\IncidenciaController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MisIncidenciaController;
use App\Http\Controllers\Admin\ModoController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SubcategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\EstatuController;
use App\Models\Estatu;
use Illuminate\Support\Facades\Route;

Route::get('', [HomeController::class, 'index'])->middleware('can:admin.home')->name('admin.home');

Route::resource('users', UserController::class)->only(['index', 'edit', 'update'])->names('admin.users');

Route::resource('roles', RoleController::class)->names('admin.roles');

Route::resource('categories', CategoryController::class)->except('show')->names('admin.categories');

Route::resource('subcategories', SubcategoryController::class)->except('show')->names('admin.subcategories');

// Route::resource('modos', ModoController::class)->except('show')->names('admin.modos');
Route::resource('estatus', EstatuController::class)->except('show')->names('admin.estatus');

Route::resource('incidencias', IncidenciaController::class)->except('show')->names('admin.incidencias');

Route::resource('mis-incidencias', MisIncidenciaController::class)->except('show')->names('admin.mis-incidencias');

routes/web.php
<?php

use App\Http\Controllers\IncidenciaController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SuscripcionController;
use Illuminate\Support\Facades\Route;



// Route::get('/',[IncidenciaController::class, 'index'])->name('incidencias.index');
Route::get('/',[IncidenciaController::class, 'index'])->name('incidencias.index')->middleware('auth');

Route::get('incidencias/{incidencia}',[IncidenciaController::class, 'show'])->name('incidencias.show');

Route::get('category/{category}', [IncidenciaController::class, 'category'])->name('incidencias.category');

// Route::get('modo/{modo}', [IncidenciaController::class, 'modo'])->name('incidencias.modo');

// Route::resource('suscripciones', SuscripcionController::class)->names('suscripciones');


/* Mensaje */
Route::post('/mensajes',[MessageController::class, 'store'])->name('mensajes.store');


Route::get('markAsRead', function () {
    auth()->user()->unreadNotifications->markAsRead();
    return redirect()->back();
})->name('markAsRead');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

resources/views/admin/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Tablero</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">

            <h3>{{ Auth::user()->name }}</h3>
            <h5>Bienvenido al sistema</h5>

        </div>
        
        @if (Auth::user()->hasRole('Admin'))
        
            <div class="card-body">

                <div class="row">

                    <div class="col-lg-3 col-6">
                        
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{ $incidencias->count() }}</h3>
                                <p>Incidencias</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="{{route('admin.incidencias.index')}}" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>

                <div class="row">
                    
                    <div class="col-lg-3 col-6">
                    
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>{{ $incidencias->where('estatu_id', 1)->count() }} ({{ round($incidencias->where('estatu_id', 1)->count() * 100 / $incidencias->count() ,1) }}<sup style="font-size: 20px">%</sup>)</h3>
                                <p>{{ $estatus->where('id', 1)->first()->name }}</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            {{-- <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a> --}}
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">
                    
                        <div class="small-box bg-blue">
                            <div class="inner">
                                <h3>{{ $incidencias->where('estatu_id', 2)->count() }} ({{ round($incidencias->where('estatu_id', 2)->count() * 100 / $incidencias->count() ,1) }}<sup style="font-size: 20px">%</sup>)</h3>
                                <p>{{ $estatus->where('id', 2)->first()->name }}</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            {{-- <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a> --}}
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">
                    
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>{{ $incidencias->where('estatu_id', 3)->count() }} ({{ round($incidencias->where('estatu_id', 3)->count() * 100 / $incidencias->count() ,1) }}<sup style="font-size: 20px">%</sup>)</h3>
                                <p>{{ $estatus->where('id', 3)->first()->name }}</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            {{-- <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a> --}}
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-6">
                    
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3>{{ $incidencias->where('estatu_id', 4)->count() }} ({{ round($incidencias->where('estatu_id', 4)->count() * 100 / $incidencias->count() ,1) }}<sup style="font-size: 20px">%</sup>)</h3>
                                <p>{{ $estatus->where('id', 4)->first()->name }}</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            {{-- <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a> --}}
                        </div>
                    </div>
                    
                </div>

            </div>
        
        @endif
    </div>   
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop